[tool.poetry]
name = "plex-auto-skip"
version = "0.1.0"
description = ""
authors = ["sprt <hellosprt@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
PlexAPI = "^4.2.0"
requests = "^2.25.1"
websocket_client = "^0.57.0"  # For PlexAPI's AlertListener

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
